

package dev.zacsweers.metro.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.zacsweers.metro.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/box/aggregation")
@TestDataPath("$PROJECT_ROOT")
public class ContributionProvidersBoxTestGenerated extends AbstractContributionProvidersBoxTest {
  @Test
  public void testAllFilesPresentInAggregation() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/box/aggregation"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("AnyIsAValidSupertype.kt")
  public void testAnyIsAValidSupertype() {
    runTest("compiler-tests/src/test/data/box/aggregation/AnyIsAValidSupertype.kt");
  }

  @Test
  @TestMetadata("BindingReplacementFromClassWithMultipleBindingsInGraphExtension.kt")
  public void testBindingReplacementFromClassWithMultipleBindingsInGraphExtension() {
    runTest("compiler-tests/src/test/data/box/aggregation/BindingReplacementFromClassWithMultipleBindingsInGraphExtension.kt");
  }

  @Test
  @TestMetadata("ComputedPropertiesIntoSet.kt")
  public void testComputedPropertiesIntoSet() {
    runTest("compiler-tests/src/test/data/box/aggregation/ComputedPropertiesIntoSet.kt");
  }

  @Test
  @TestMetadata("ContributedBindingContainerExclusions.kt")
  public void testContributedBindingContainerExclusions() {
    runTest("compiler-tests/src/test/data/box/aggregation/ContributedBindingContainerExclusions.kt");
  }

  @Test
  @TestMetadata("ContributedBindingContainerGetsExcluded.kt")
  public void testContributedBindingContainerGetsExcluded() {
    runTest("compiler-tests/src/test/data/box/aggregation/ContributedBindingContainerGetsExcluded.kt");
  }

  @Test
  @TestMetadata("ContributedBindingContainerGetsExcludedInContributedGraph.kt")
  public void testContributedBindingContainerGetsExcludedInContributedGraph() {
    runTest("compiler-tests/src/test/data/box/aggregation/ContributedBindingContainerGetsExcludedInContributedGraph.kt");
  }

  @Test
  @TestMetadata("ContributedBindingContainerReplacements.kt")
  public void testContributedBindingContainerReplacements() {
    runTest("compiler-tests/src/test/data/box/aggregation/ContributedBindingContainerReplacements.kt");
  }

  @Test
  @TestMetadata("ContributedBindingContainerReplacesContributedBinding.kt")
  public void testContributedBindingContainerReplacesContributedBinding() {
    runTest("compiler-tests/src/test/data/box/aggregation/ContributedBindingContainerReplacesContributedBinding.kt");
  }

  @Test
  @TestMetadata("ContributedBindingContainerReplacesContributedBindingInContributedGraph.kt")
  public void testContributedBindingContainerReplacesContributedBindingInContributedGraph() {
    runTest("compiler-tests/src/test/data/box/aggregation/ContributedBindingContainerReplacesContributedBindingInContributedGraph.kt");
  }

  @Test
  @TestMetadata("ContributedGraphBindingContainerExcludedFromParent.kt")
  public void testContributedGraphBindingContainerExcludedFromParent() {
    runTest("compiler-tests/src/test/data/box/aggregation/ContributedGraphBindingContainerExcludedFromParent.kt");
  }

  @Test
  @TestMetadata("ContributesBindingScopeArgumentOrder.kt")
  public void testContributesBindingScopeArgumentOrder() {
    runTest("compiler-tests/src/test/data/box/aggregation/ContributesBindingScopeArgumentOrder.kt");
  }

  @Test
  @TestMetadata("ContributingMultibileNullableBindings.kt")
  public void testContributingMultibileNullableBindings() {
    runTest("compiler-tests/src/test/data/box/aggregation/ContributingMultibileNullableBindings.kt");
  }

  @Test
  @TestMetadata("DefaultBinding_Basic.kt")
  public void testDefaultBinding_Basic() {
    runTest("compiler-tests/src/test/data/box/aggregation/DefaultBinding_Basic.kt");
  }

  @Test
  @TestMetadata("DefaultBinding_ExplicitOverride.kt")
  public void testDefaultBinding_ExplicitOverride() {
    runTest("compiler-tests/src/test/data/box/aggregation/DefaultBinding_ExplicitOverride.kt");
  }

  @Test
  @TestMetadata("DefaultBinding_IntoSet.kt")
  public void testDefaultBinding_IntoSet() {
    runTest("compiler-tests/src/test/data/box/aggregation/DefaultBinding_IntoSet.kt");
  }

  @Test
  @TestMetadata("DefaultBinding_NearestSupertypeWins.kt")
  public void testDefaultBinding_NearestSupertypeWins() {
    runTest("compiler-tests/src/test/data/box/aggregation/DefaultBinding_NearestSupertypeWins.kt");
  }

  @Test
  @TestMetadata("DefaultBinding_WithGenericType.kt")
  public void testDefaultBinding_WithGenericType() {
    runTest("compiler-tests/src/test/data/box/aggregation/DefaultBinding_WithGenericType.kt");
  }

  @Test
  @TestMetadata("ExcludeBindingContainerWithOrigin.kt")
  public void testExcludeBindingContainerWithOrigin() {
    runTest("compiler-tests/src/test/data/box/aggregation/ExcludeBindingContainerWithOrigin.kt");
  }

  @Test
  @TestMetadata("ExcludeBindingContainerWithOriginInExtension.kt")
  public void testExcludeBindingContainerWithOriginInExtension() {
    runTest("compiler-tests/src/test/data/box/aggregation/ExcludeBindingContainerWithOriginInExtension.kt");
  }

  @Test
  @TestMetadata("ExcludeContributedGraphExtension.kt")
  public void testExcludeContributedGraphExtension() {
    runTest("compiler-tests/src/test/data/box/aggregation/ExcludeContributedGraphExtension.kt");
  }

  @Test
  @TestMetadata("ExcludedBindingContainerReplacesEffectIgnored.kt")
  public void testExcludedBindingContainerReplacesEffectIgnored() {
    runTest("compiler-tests/src/test/data/box/aggregation/ExcludedBindingContainerReplacesEffectIgnored.kt");
  }

  @Test
  @TestMetadata("ExcludedBindingContainerReplacesEffectIgnoredMultiModule.kt")
  public void testExcludedBindingContainerReplacesEffectIgnoredMultiModule() {
    runTest("compiler-tests/src/test/data/box/aggregation/ExcludedBindingContainerReplacesEffectIgnoredMultiModule.kt");
  }

  @Test
  @TestMetadata("ExcludesWithOrigin.kt")
  public void testExcludesWithOrigin() {
    runTest("compiler-tests/src/test/data/box/aggregation/ExcludesWithOrigin.kt");
  }

  @Test
  @TestMetadata("ExcludesWithOriginInExtension.kt")
  public void testExcludesWithOriginInExtension() {
    runTest("compiler-tests/src/test/data/box/aggregation/ExcludesWithOriginInExtension.kt");
  }

  @Test
  @TestMetadata("InheritedBindingsDoNotCauseDuplicatesFromNestedContainers.kt")
  public void testInheritedBindingsDoNotCauseDuplicatesFromNestedContainers() {
    runTest("compiler-tests/src/test/data/box/aggregation/InheritedBindingsDoNotCauseDuplicatesFromNestedContainers.kt");
  }

  @Test
  @TestMetadata("InternalHintsInContributedGraph.kt")
  public void testInternalHintsInContributedGraph() {
    runTest("compiler-tests/src/test/data/box/aggregation/InternalHintsInContributedGraph.kt");
  }

  @Test
  @TestMetadata("InternalHintsInGraph.kt")
  public void testInternalHintsInGraph() {
    runTest("compiler-tests/src/test/data/box/aggregation/InternalHintsInGraph.kt");
  }

  @Test
  @TestMetadata("MapKeyNotCopiedForNonIntoMapBinding.kt")
  public void testMapKeyNotCopiedForNonIntoMapBinding() {
    runTest("compiler-tests/src/test/data/box/aggregation/MapKeyNotCopiedForNonIntoMapBinding.kt");
  }

  @Test
  @TestMetadata("MultipleBindingReplacementsFromSameClass.kt")
  public void testMultipleBindingReplacementsFromSameClass() {
    runTest("compiler-tests/src/test/data/box/aggregation/MultipleBindingReplacementsFromSameClass.kt");
  }

  @Test
  @TestMetadata("MultipleBindingReplacementsFromSameClassAndSameModule.kt")
  public void testMultipleBindingReplacementsFromSameClassAndSameModule() {
    runTest("compiler-tests/src/test/data/box/aggregation/MultipleBindingReplacementsFromSameClassAndSameModule.kt");
  }

  @Test
  @TestMetadata("MultipleBindingReplacementsFromSameClassAndSameModuleAndDifferentScopes.kt")
  public void testMultipleBindingReplacementsFromSameClassAndSameModuleAndDifferentScopes() {
    runTest("compiler-tests/src/test/data/box/aggregation/MultipleBindingReplacementsFromSameClassAndSameModuleAndDifferentScopes.kt");
  }

  @Test
  @TestMetadata("MultipleBindingReplacementsFromSameClassDifferentScopes.kt")
  public void testMultipleBindingReplacementsFromSameClassDifferentScopes() {
    runTest("compiler-tests/src/test/data/box/aggregation/MultipleBindingReplacementsFromSameClassDifferentScopes.kt");
  }

  @Test
  @TestMetadata("ReplacementsWithOrigin.kt")
  public void testReplacementsWithOrigin() {
    runTest("compiler-tests/src/test/data/box/aggregation/ReplacementsWithOrigin.kt");
  }

  @Test
  @TestMetadata("ReplacementsWithOriginInContributedGraphExtensionSet.kt")
  public void testReplacementsWithOriginInContributedGraphExtensionSet() {
    runTest("compiler-tests/src/test/data/box/aggregation/ReplacementsWithOriginInContributedGraphExtensionSet.kt");
  }

  @Test
  @TestMetadata("ReplacementsWithOriginInExtension.kt")
  public void testReplacementsWithOriginInExtension() {
    runTest("compiler-tests/src/test/data/box/aggregation/ReplacementsWithOriginInExtension.kt");
  }

  @Test
  @TestMetadata("ReplacementsWorkInGraphExtensions.kt")
  public void testReplacementsWorkInGraphExtensions() {
    runTest("compiler-tests/src/test/data/box/aggregation/ReplacementsWorkInGraphExtensions.kt");
  }

  @Test
  @TestMetadata("ScopedContributedBindingCanBeAccessedFromChildWithClassHintsEnabled.kt")
  public void testScopedContributedBindingCanBeAccessedFromChildWithClassHintsEnabled() {
    runTest("compiler-tests/src/test/data/box/aggregation/ScopedContributedBindingCanBeAccessedFromChildWithClassHintsEnabled.kt");
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/box/aggregation/contributionproviders")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributionproviders {
    @Test
    @TestMetadata("abstractedAssistedFactoryIsAccessibleExternally.kt")
    public void testAbstractedAssistedFactoryIsAccessibleExternally() {
      runTest("compiler-tests/src/test/data/box/aggregation/contributionproviders/abstractedAssistedFactoryIsAccessibleExternally.kt");
    }

    @Test
    public void testAllFilesPresentInContributionproviders() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/box/aggregation/contributionproviders"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("basic.kt")
    public void testBasic() {
      runTest("compiler-tests/src/test/data/box/aggregation/contributionproviders/basic.kt");
    }

    @Test
    @TestMetadata("defaultParameters.kt")
    public void testDefaultParameters() {
      runTest("compiler-tests/src/test/data/box/aggregation/contributionproviders/defaultParameters.kt");
    }

    @Test
    @TestMetadata("explicitMultibindingType.kt")
    public void testExplicitMultibindingType() {
      runTest("compiler-tests/src/test/data/box/aggregation/contributionproviders/explicitMultibindingType.kt");
    }

    @Test
    @TestMetadata("exposeImplBinding.kt")
    public void testExposeImplBinding() {
      runTest("compiler-tests/src/test/data/box/aggregation/contributionproviders/exposeImplBinding.kt");
    }

    @Test
    @TestMetadata("implTypeNotDirectlyAccessible.kt")
    public void testImplTypeNotDirectlyAccessible() {
      runTest("compiler-tests/src/test/data/box/aggregation/contributionproviders/implTypeNotDirectlyAccessible.kt");
    }

    @Test
    @TestMetadata("implicitClassKeyMapKey.kt")
    public void testImplicitClassKeyMapKey() {
      runTest("compiler-tests/src/test/data/box/aggregation/contributionproviders/implicitClassKeyMapKey.kt");
    }

    @Test
    @TestMetadata("intoMap.kt")
    public void testIntoMap() {
      runTest("compiler-tests/src/test/data/box/aggregation/contributionproviders/intoMap.kt");
    }

    @Test
    @TestMetadata("intoSet.kt")
    public void testIntoSet() {
      runTest("compiler-tests/src/test/data/box/aggregation/contributionproviders/intoSet.kt");
    }

    @Test
    @TestMetadata("multipleBindings.kt")
    public void testMultipleBindings() {
      runTest("compiler-tests/src/test/data/box/aggregation/contributionproviders/multipleBindings.kt");
    }

    @Test
    @TestMetadata("objectBinding.kt")
    public void testObjectBinding() {
      runTest("compiler-tests/src/test/data/box/aggregation/contributionproviders/objectBinding.kt");
    }

    @Test
    @TestMetadata("privateConstructorSkipped.kt")
    public void testPrivateConstructorSkipped() {
      runTest("compiler-tests/src/test/data/box/aggregation/contributionproviders/privateConstructorSkipped.kt");
    }

    @Test
    @TestMetadata("providerAndLazy.kt")
    public void testProviderAndLazy() {
      runTest("compiler-tests/src/test/data/box/aggregation/contributionproviders/providerAndLazy.kt");
    }

    @Test
    @TestMetadata("qualifiedBinding.kt")
    public void testQualifiedBinding() {
      runTest("compiler-tests/src/test/data/box/aggregation/contributionproviders/qualifiedBinding.kt");
    }

    @Test
    @TestMetadata("scoped.kt")
    public void testScoped() {
      runTest("compiler-tests/src/test/data/box/aggregation/contributionproviders/scoped.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/box/aggregation/interop")
  @TestDataPath("$PROJECT_ROOT")
  public class Interop {
    @Test
    public void testAllFilesPresentInInterop() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/box/aggregation/interop"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("ContributedBindingContainerExclusions.kt")
    public void testContributedBindingContainerExclusions() {
      runTest("compiler-tests/src/test/data/box/aggregation/interop/ContributedBindingContainerExclusions.kt");
    }

    @Test
    @TestMetadata("ContributedGraphBindingContainerExclusions.kt")
    public void testContributedGraphBindingContainerExclusions() {
      runTest("compiler-tests/src/test/data/box/aggregation/interop/ContributedGraphBindingContainerExclusions.kt");
    }

    @Test
    @TestMetadata("ContributedGraphExtensionGetsExcluded.kt")
    public void testContributedGraphExtensionGetsExcluded() {
      runTest("compiler-tests/src/test/data/box/aggregation/interop/ContributedGraphExtensionGetsExcluded.kt");
    }

    @Test
    @TestMetadata("ContributedGraphsSupportIgnoreQualifier.kt")
    public void testContributedGraphsSupportIgnoreQualifier() {
      runTest("compiler-tests/src/test/data/box/aggregation/interop/ContributedGraphsSupportIgnoreQualifier.kt");
    }

    @Test
    @TestMetadata("ContributedGraphsSupportRankings.kt")
    public void testContributedGraphsSupportRankings() {
      runTest("compiler-tests/src/test/data/box/aggregation/interop/ContributedGraphsSupportRankings.kt");
    }

    @Test
    @TestMetadata("ContributesBindingMixedRegularAndMultibinding.kt")
    public void testContributesBindingMixedRegularAndMultibinding() {
      runTest("compiler-tests/src/test/data/box/aggregation/interop/ContributesBindingMixedRegularAndMultibinding.kt");
    }

    @Test
    @TestMetadata("ContributesBindingMultibindingInterop.kt")
    public void testContributesBindingMultibindingInterop() {
      runTest("compiler-tests/src/test/data/box/aggregation/interop/ContributesBindingMultibindingInterop.kt");
    }

    @Test
    @TestMetadata("ContributesBindingMultibindingWithExplicitBoundType.kt")
    public void testContributesBindingMultibindingWithExplicitBoundType() {
      runTest("compiler-tests/src/test/data/box/aggregation/interop/ContributesBindingMultibindingWithExplicitBoundType.kt");
    }

    @Test
    @TestMetadata("ContributesMultibindingInteropAnnotationsAddBindingToSetOrMapWithMapKey.kt")
    public void testContributesMultibindingInteropAnnotationsAddBindingToSetOrMapWithMapKey() {
      runTest("compiler-tests/src/test/data/box/aggregation/interop/ContributesMultibindingInteropAnnotationsAddBindingToSetOrMapWithMapKey.kt");
    }

    @Test
    @TestMetadata("ExcludesWithOriginInterop.kt")
    public void testExcludesWithOriginInterop() {
      runTest("compiler-tests/src/test/data/box/aggregation/interop/ExcludesWithOriginInterop.kt");
    }

    @Test
    @TestMetadata("RankBasedReplacementFromClassWithMultipleBindingsInGraphExtension.kt")
    public void testRankBasedReplacementFromClassWithMultipleBindingsInGraphExtension() {
      runTest("compiler-tests/src/test/data/box/aggregation/interop/RankBasedReplacementFromClassWithMultipleBindingsInGraphExtension.kt");
    }

    @Test
    @TestMetadata("RankBasedReplacementFromClassWithMultipleBindingsInRootGraph.kt")
    public void testRankBasedReplacementFromClassWithMultipleBindingsInRootGraph() {
      runTest("compiler-tests/src/test/data/box/aggregation/interop/RankBasedReplacementFromClassWithMultipleBindingsInRootGraph.kt");
    }

    @Test
    @TestMetadata("RepeatedContributesBindingAnvilInteropWorksForBoundTypeAndIgnoreQualifier.kt")
    public void testRepeatedContributesBindingAnvilInteropWorksForBoundTypeAndIgnoreQualifier() {
      runTest("compiler-tests/src/test/data/box/aggregation/interop/RepeatedContributesBindingAnvilInteropWorksForBoundTypeAndIgnoreQualifier.kt");
    }
  }
}
