

package dev.zacsweers.metro.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.zacsweers.metro.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/dump/ir")
@TestDataPath("$PROJECT_ROOT")
public class IrDumpTestGenerated extends AbstractIrDumpTest {
  @Test
  public void testAllFilesPresentInIr() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("AssistedInjectClassFactoriesGetReused.kt")
  public void testAssistedInjectClassFactoriesGetReused() {
    runTest("compiler-tests/src/test/data/dump/ir/AssistedInjectClassFactoriesGetReused.kt");
  }

  @Test
  @TestMetadata("MultibindingsHaveConsistentOrderAcrossContributedGraph.kt")
  public void testMultibindingsHaveConsistentOrderAcrossContributedGraph() {
    runTest("compiler-tests/src/test/data/dump/ir/MultibindingsHaveConsistentOrderAcrossContributedGraph.kt");
  }

  @Test
  @TestMetadata("MultibindingsWithComplexDependenciesGetProperties.kt")
  public void testMultibindingsWithComplexDependenciesGetProperties() {
    runTest("compiler-tests/src/test/data/dump/ir/MultibindingsWithComplexDependenciesGetProperties.kt");
  }

  @Test
  @TestMetadata("scratch.kt")
  public void testScratch() {
    runTest("compiler-tests/src/test/data/dump/ir/scratch.kt");
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/ir/aggregation")
  @TestDataPath("$PROJECT_ROOT")
  public class Aggregation {
    @Test
    public void testAllFilesPresentInAggregation() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/aggregation"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("ContributionProviders_BasicDump.kt")
    public void testContributionProviders_BasicDump() {
      runTest("compiler-tests/src/test/data/dump/ir/aggregation/ContributionProviders_BasicDump.kt");
    }

    @Test
    @TestMetadata("ContributionProviders_ScopedMultipleBindings.kt")
    public void testContributionProviders_ScopedMultipleBindings() {
      runTest("compiler-tests/src/test/data/dump/ir/aggregation/ContributionProviders_ScopedMultipleBindings.kt");
    }

    @Test
    @TestMetadata("ContributorsWithSameSimpleNames.kt")
    public void testContributorsWithSameSimpleNames() {
      runTest("compiler-tests/src/test/data/dump/ir/aggregation/ContributorsWithSameSimpleNames.kt");
    }

    @Test
    @TestMetadata("ContributorsWithSameSimpleNamesSameOrigin.kt")
    public void testContributorsWithSameSimpleNamesSameOrigin() {
      runTest("compiler-tests/src/test/data/dump/ir/aggregation/ContributorsWithSameSimpleNamesSameOrigin.kt");
    }

    @Test
    @TestMetadata("DefaultBindingMirror.kt")
    public void testDefaultBindingMirror() {
      runTest("compiler-tests/src/test/data/dump/ir/aggregation/DefaultBindingMirror.kt");
    }

    @Test
    @TestMetadata("ImplicitClassKeyPopulatedOnCopy.kt")
    public void testImplicitClassKeyPopulatedOnCopy() {
      runTest("compiler-tests/src/test/data/dump/ir/aggregation/ImplicitClassKeyPopulatedOnCopy.kt");
    }

    @Test
    @TestMetadata("MultipleContributionsOnlyProduceOneHintFile.kt")
    public void testMultipleContributionsOnlyProduceOneHintFile() {
      runTest("compiler-tests/src/test/data/dump/ir/aggregation/MultipleContributionsOnlyProduceOneHintFile.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/ir/cycles")
  @TestDataPath("$PROJECT_ROOT")
  public class Cycles {
    @Test
    public void testAllFilesPresentInCycles() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/cycles"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("BindsCycleGraph.kt")
    public void testBindsCycleGraph() {
      runTest("compiler-tests/src/test/data/dump/ir/cycles/BindsCycleGraph.kt");
    }

    @Test
    @TestMetadata("CycleGraph.kt")
    public void testCycleGraph() {
      runTest("compiler-tests/src/test/data/dump/ir/cycles/CycleGraph.kt");
    }

    @Test
    @TestMetadata("CycleMapGraph.kt")
    public void testCycleMapGraph() {
      runTest("compiler-tests/src/test/data/dump/ir/cycles/CycleMapGraph.kt");
    }

    @Test
    @TestMetadata("SelfCycle.kt")
    public void testSelfCycle() {
      runTest("compiler-tests/src/test/data/dump/ir/cycles/SelfCycle.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/ir/dependencygraph")
  @TestDataPath("$PROJECT_ROOT")
  public class Dependencygraph {
    @Test
    public void testAllFilesPresentInDependencygraph() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/dependencygraph"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("CreatorParamsDoNotGetChunked.kt")
    public void testCreatorParamsDoNotGetChunked() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/CreatorParamsDoNotGetChunked.kt");
    }

    @Test
    @TestMetadata("EmptyMapMultibindingsUseEmptyMap.kt")
    public void testEmptyMapMultibindingsUseEmptyMap() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/EmptyMapMultibindingsUseEmptyMap.kt");
    }

    @Test
    @TestMetadata("ExtensionsAreInnerClasses.kt")
    public void testExtensionsAreInnerClasses() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/ExtensionsAreInnerClasses.kt");
    }

    @Test
    @TestMetadata("GraphAccessors.kt")
    public void testGraphAccessors() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/GraphAccessors.kt");
    }

    @Test
    @TestMetadata("GraphImplClassAsReturnType.kt")
    public void testGraphImplClassAsReturnType() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/GraphImplClassAsReturnType.kt");
    }

    @Test
    @TestMetadata("InitsAreChunked.kt")
    public void testInitsAreChunked() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/InitsAreChunked.kt");
    }

    @Test
    @TestMetadata("LazyPropertiesHaveDeterministicOrder.kt")
    public void testLazyPropertiesHaveDeterministicOrder() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/LazyPropertiesHaveDeterministicOrder.kt");
    }

    @Test
    @TestMetadata("MapBuildersUseInlineInstantiation.kt")
    public void testMapBuildersUseInlineInstantiation() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/MapBuildersUseInlineInstantiation.kt");
    }

    @Test
    @TestMetadata("MapsUseMapBuilderIfNoProvider.kt")
    public void testMapsUseMapBuilderIfNoProvider() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/MapsUseMapBuilderIfNoProvider.kt");
    }

    @Test
    @TestMetadata("MixedUseFactoryAcrossMultipleMultis.kt")
    public void testMixedUseFactoryAcrossMultipleMultis() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/MixedUseFactoryAcrossMultipleMultis.kt");
    }

    @Test
    @TestMetadata("MixedUseFactoryAcrossMultipleNestedMiddleMultis.kt")
    public void testMixedUseFactoryAcrossMultipleNestedMiddleMultis() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/MixedUseFactoryAcrossMultipleNestedMiddleMultis.kt");
    }

    @Test
    @TestMetadata("MixedUseFactoryAndScalarRefsShouldUseOneProviderField.kt")
    public void testMixedUseFactoryAndScalarRefsShouldUseOneProviderField() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/MixedUseFactoryAndScalarRefsShouldUseOneProviderField.kt");
    }

    @Test
    @TestMetadata("MultipleRefsGetProviderFields.kt")
    public void testMultipleRefsGetProviderFields() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/MultipleRefsGetProviderFields.kt");
    }

    @Test
    @TestMetadata("NestedClassNamesInDump.kt")
    public void testNestedClassNamesInDump() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/NestedClassNamesInDump.kt");
    }

    @Test
    @TestMetadata("OptionalBindingsHaveValidFieldNames.kt")
    public void testOptionalBindingsHaveValidFieldNames() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/OptionalBindingsHaveValidFieldNames.kt");
    }

    @Test
    @TestMetadata("ProviderAccessorsAreTrackedInRefCounting.kt")
    public void testProviderAccessorsAreTrackedInRefCounting() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/ProviderAccessorsAreTrackedInRefCounting.kt");
    }

    @Test
    @TestMetadata("RefCountingFollowsAliases.kt")
    public void testRefCountingFollowsAliases() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/RefCountingFollowsAliases.kt");
    }

    @Test
    @TestMetadata("ReusableScalarBindings.kt")
    public void testReusableScalarBindings() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/ReusableScalarBindings.kt");
    }

    @Test
    @TestMetadata("UnusedInstanceBindingsInUnextendedGraphGetNoProviderFields.kt")
    public void testUnusedInstanceBindingsInUnextendedGraphGetNoProviderFields() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/UnusedInstanceBindingsInUnextendedGraphGetNoProviderFields.kt");
    }

    @Test
    @TestMetadata("UnusedScopedBindingsInUnextendedGraphGetNoProviderFields.kt")
    public void testUnusedScopedBindingsInUnextendedGraphGetNoProviderFields() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/UnusedScopedBindingsInUnextendedGraphGetNoProviderFields.kt");
    }

    @Test
    @TestMetadata("UnusedScopedConstructorInjectedClassWithConstructorAnnotatedIsDiscovered.kt")
    public void testUnusedScopedConstructorInjectedClassWithConstructorAnnotatedIsDiscovered() {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/UnusedScopedConstructorInjectedClassWithConstructorAnnotatedIsDiscovered.kt");
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/dump/ir/dependencygraph/dynamic")
    @TestDataPath("$PROJECT_ROOT")
    public class Dynamic {
      @Test
      public void testAllFilesPresentInDynamic() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/dependencygraph/dynamic"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("SimpleDynamicGraph.kt")
      public void testSimpleDynamicGraph() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/dynamic/SimpleDynamicGraph.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/dump/ir/dependencygraph/interop")
    @TestDataPath("$PROJECT_ROOT")
    public class Interop {
      @Test
      public void testAllFilesPresentInInterop() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/dependencygraph/interop"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("BindsOptionalOfUsesLazyProviders.kt")
      public void testBindsOptionalOfUsesLazyProviders() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/interop/BindsOptionalOfUsesLazyProviders.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding")
    @TestDataPath("$PROJECT_ROOT")
    public class Sharding {
      @Test
      public void testAllFilesPresentInSharding() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("CrossShardDependencies.kt")
      public void testCrossShardDependencies() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding/CrossShardDependencies.kt");
      }

      @Test
      @TestMetadata("MinimalGraphSharding.kt")
      public void testMinimalGraphSharding() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding/MinimalGraphSharding.kt");
      }

      @Test
      @TestMetadata("MinimalGraphShardingDisabled.kt")
      public void testMinimalGraphShardingDisabled() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding/MinimalGraphShardingDisabled.kt");
      }

      @Test
      @TestMetadata("MinimalGraphShardingTooSmall.kt")
      public void testMinimalGraphShardingTooSmall() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding/MinimalGraphShardingTooSmall.kt");
      }

      @Test
      @TestMetadata("ShardedGraphWithChainedExtensions.kt")
      public void testShardedGraphWithChainedExtensions() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding/ShardedGraphWithChainedExtensions.kt");
      }

      @Test
      @TestMetadata("ShardedGraphWithMultipleExtensions.kt")
      public void testShardedGraphWithMultipleExtensions() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding/ShardedGraphWithMultipleExtensions.kt");
      }

      @Test
      @TestMetadata("ShardingWithBinds.kt")
      public void testShardingWithBinds() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding/ShardingWithBinds.kt");
      }

      @Test
      @TestMetadata("ShardingWithChunkedInit.kt")
      public void testShardingWithChunkedInit() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding/ShardingWithChunkedInit.kt");
      }

      @Test
      @TestMetadata("ShardingWithCycle.kt")
      public void testShardingWithCycle() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding/ShardingWithCycle.kt");
      }

      @Test
      @TestMetadata("ShardingWithMultibindings.kt")
      public void testShardingWithMultibindings() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding/ShardingWithMultibindings.kt");
      }

      @Test
      @TestMetadata("ShardingWithProvides.kt")
      public void testShardingWithProvides() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding/ShardingWithProvides.kt");
      }

      @Test
      @TestMetadata("ThreeShardsWithOrder.kt")
      public void testThreeShardsWithOrder() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding/ThreeShardsWithOrder.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/dump/ir/dependencygraph/switchingproviders")
    @TestDataPath("$PROJECT_ROOT")
    public class Switchingproviders {
      @Test
      public void testAllFilesPresentInSwitchingproviders() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/dependencygraph/switchingproviders"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("ChunkedSwitchingProvider.kt")
      public void testChunkedSwitchingProvider() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/switchingproviders/ChunkedSwitchingProvider.kt");
      }

      @Test
      @TestMetadata("SimpleSwitchingProvider.kt")
      public void testSimpleSwitchingProvider() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/switchingproviders/SimpleSwitchingProvider.kt");
      }

      @Test
      @TestMetadata("SimpleSwitchingProviderWithShards.kt")
      public void testSimpleSwitchingProviderWithShards() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/switchingproviders/SimpleSwitchingProviderWithShards.kt");
      }

      @Test
      @TestMetadata("SwitchingProvidersAcrossExtensions.kt")
      public void testSwitchingProvidersAcrossExtensions() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/switchingproviders/SwitchingProvidersAcrossExtensions.kt");
      }

      @Test
      @TestMetadata("SwitchingProvidersWithBindsOptional.kt")
      public void testSwitchingProvidersWithBindsOptional() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/switchingproviders/SwitchingProvidersWithBindsOptional.kt");
      }

      @Test
      @TestMetadata("SwitchingProvidersWithCycles.kt")
      public void testSwitchingProvidersWithCycles() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/switchingproviders/SwitchingProvidersWithCycles.kt");
      }

      @Test
      @TestMetadata("SwitchingProvidersWithMembersInjectProvider.kt")
      public void testSwitchingProvidersWithMembersInjectProvider() {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/switchingproviders/SwitchingProvidersWithMembersInjectProvider.kt");
      }
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/ir/injectconstructor")
  @TestDataPath("$PROJECT_ROOT")
  public class Injectconstructor {
    @Test
    public void testAllFilesPresentInInjectconstructor() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/injectconstructor"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("ConstructorFunctionSignatures.kt")
    public void testConstructorFunctionSignatures() {
      runTest("compiler-tests/src/test/data/dump/ir/injectconstructor/ConstructorFunctionSignatures.kt");
    }

    @Test
    @TestMetadata("DefaultValuesPropagateToNewInstanceParams.kt")
    public void testDefaultValuesPropagateToNewInstanceParams() {
      runTest("compiler-tests/src/test/data/dump/ir/injectconstructor/DefaultValuesPropagateToNewInstanceParams.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/ir/multibindings")
  @TestDataPath("$PROJECT_ROOT")
  public class Multibindings {
    @Test
    public void testAllFilesPresentInMultibindings() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/multibindings"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("ElementsIntoSetWorkInScalars.kt")
    public void testElementsIntoSetWorkInScalars() {
      runTest("compiler-tests/src/test/data/dump/ir/multibindings/ElementsIntoSetWorkInScalars.kt");
    }

    @Test
    @TestMetadata("ElementsIntoSetWorkInScalarsMixed.kt")
    public void testElementsIntoSetWorkInScalarsMixed() {
      runTest("compiler-tests/src/test/data/dump/ir/multibindings/ElementsIntoSetWorkInScalarsMixed.kt");
    }

    @Test
    @TestMetadata("InjectorFunctionsDoNotTriggerProviderGets.kt")
    public void testInjectorFunctionsDoNotTriggerProviderGets() {
      runTest("compiler-tests/src/test/data/dump/ir/multibindings/InjectorFunctionsDoNotTriggerProviderGets.kt");
    }

    @Test
    @TestMetadata("MapProvidersParticipateInProviderRefcounting.kt")
    public void testMapProvidersParticipateInProviderRefcounting() {
      runTest("compiler-tests/src/test/data/dump/ir/multibindings/MapProvidersParticipateInProviderRefcounting.kt");
    }

    @Test
    @TestMetadata("MultibindingInParentMemberInjectedClass.kt")
    public void testMultibindingInParentMemberInjectedClass() {
      runTest("compiler-tests/src/test/data/dump/ir/multibindings/MultibindingInParentMemberInjectedClass.kt");
    }

    @Test
    @TestMetadata("MultibindingProviderAccessPropagatesRefCount.kt")
    public void testMultibindingProviderAccessPropagatesRefCount() {
      runTest("compiler-tests/src/test/data/dump/ir/multibindings/MultibindingProviderAccessPropagatesRefCount.kt");
    }

    @Test
    @TestMetadata("MultibindingRefCountFromFactoryPath.kt")
    public void testMultibindingRefCountFromFactoryPath() {
      runTest("compiler-tests/src/test/data/dump/ir/multibindings/MultibindingRefCountFromFactoryPath.kt");
    }

    @Test
    @TestMetadata("MultibindingSourcesGetGettersThroughAliases.kt")
    public void testMultibindingSourcesGetGettersThroughAliases() {
      runTest("compiler-tests/src/test/data/dump/ir/multibindings/MultibindingSourcesGetGettersThroughAliases.kt");
    }

    @Test
    @TestMetadata("MultibindingSourcesGetRefcountedViaFactoryPath.kt")
    public void testMultibindingSourcesGetRefcountedViaFactoryPath() {
      runTest("compiler-tests/src/test/data/dump/ir/multibindings/MultibindingSourcesGetRefcountedViaFactoryPath.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/ir/provides")
  @TestDataPath("$PROJECT_ROOT")
  public class Provides {
    @Test
    public void testAllFilesPresentInProvides() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/provides"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("DefaultValuesPropagateToNewInstanceParams.kt")
    public void testDefaultValuesPropagateToNewInstanceParams() {
      runTest("compiler-tests/src/test/data/dump/ir/provides/DefaultValuesPropagateToNewInstanceParams.kt");
    }

    @Test
    @TestMetadata("JvmFieldProvidersUseFieldAccess.kt")
    public void testJvmFieldProvidersUseFieldAccess() {
      runTest("compiler-tests/src/test/data/dump/ir/provides/JvmFieldProvidersUseFieldAccess.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/ir/visibility")
  @TestDataPath("$PROJECT_ROOT")
  public class Visibility {
    @Test
    public void testAllFilesPresentInVisibility() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/visibility"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("DaggerProviderVisibility.kt")
    public void testDaggerProviderVisibility() {
      runTest("compiler-tests/src/test/data/dump/ir/visibility/DaggerProviderVisibility.kt");
    }

    @Test
    @TestMetadata("DaggerProviderVisibilityDifferentModule.kt")
    public void testDaggerProviderVisibilityDifferentModule() {
      runTest("compiler-tests/src/test/data/dump/ir/visibility/DaggerProviderVisibilityDifferentModule.kt");
    }

    @Test
    @TestMetadata("InternalVisibility.kt")
    public void testInternalVisibility() {
      runTest("compiler-tests/src/test/data/dump/ir/visibility/InternalVisibility.kt");
    }

    @Test
    @TestMetadata("InternalVisibilityDifferentModule.kt")
    public void testInternalVisibilityDifferentModule() {
      runTest("compiler-tests/src/test/data/dump/ir/visibility/InternalVisibilityDifferentModule.kt");
    }

    @Test
    @TestMetadata("ProtectedVisibility.kt")
    public void testProtectedVisibility() {
      runTest("compiler-tests/src/test/data/dump/ir/visibility/ProtectedVisibility.kt");
    }
  }
}
