

package dev.zacsweers.metro.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.zacsweers.metro.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/dump/reports")
@TestDataPath("$PROJECT_ROOT")
public class ReportsTestGenerated extends AbstractReportsTest {
  @Test
  public void testAllFilesPresentInReports() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("BasicKeysUnusedReport.kt")
  public void testBasicKeysUnusedReport() {
    runTest("compiler-tests/src/test/data/dump/reports/BasicKeysUnusedReport.kt");
  }

  @Test
  @TestMetadata("DeeplyNestedGraphsKeysPopulatedReport.kt")
  public void testDeeplyNestedGraphsKeysPopulatedReport() {
    runTest("compiler-tests/src/test/data/dump/reports/DeeplyNestedGraphsKeysPopulatedReport.kt");
  }

  @Test
  @TestMetadata("UnmatchedReplacement.kt")
  public void testUnmatchedReplacement() {
    runTest("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement.kt");
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/reports/BasicKeysUnusedReport")
  @TestDataPath("$PROJECT_ROOT")
  public class BasicKeysUnusedReport {
    @Test
    public void testAllFilesPresentInBasicKeysUnusedReport() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/BasicKeysUnusedReport"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/dump/reports/BasicKeysUnusedReport/keys-unused")
    @TestDataPath("$PROJECT_ROOT")
    public class Keys_unused {
      @Test
      public void testAllFilesPresentInKeys_unused() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/BasicKeysUnusedReport/keys-unused"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Nested
      @TestMetadata("compiler-tests/src/test/data/dump/reports/BasicKeysUnusedReport/keys-unused/AppGraph")
      @TestDataPath("$PROJECT_ROOT")
      public class AppGraph {
        @Test
        public void testAllFilesPresentInAppGraph() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/BasicKeysUnusedReport/keys-unused/AppGraph"), Pattern.compile("^(.+)\\.kt$"), null, true);
        }

        @Nested
        @TestMetadata("compiler-tests/src/test/data/dump/reports/BasicKeysUnusedReport/keys-unused/AppGraph/Impl")
        @TestDataPath("$PROJECT_ROOT")
        public class Impl {
          @Test
          public void testAllFilesPresentInImpl() {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/BasicKeysUnusedReport/keys-unused/AppGraph/Impl"), Pattern.compile("^(.+)\\.kt$"), null, true);
          }

          @Nested
          @TestMetadata("compiler-tests/src/test/data/dump/reports/BasicKeysUnusedReport/keys-unused/AppGraph/Impl/ChildGraphImpl")
          @TestDataPath("$PROJECT_ROOT")
          public class ChildGraphImpl {
            @Test
            public void testAllFilesPresentInChildGraphImpl() {
              KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/BasicKeysUnusedReport/keys-unused/AppGraph/Impl/ChildGraphImpl"), Pattern.compile("^(.+)\\.kt$"), null, true);
            }

            @Nested
            @TestMetadata("compiler-tests/src/test/data/dump/reports/BasicKeysUnusedReport/keys-unused/AppGraph/Impl/ChildGraphImpl/GrandchildGraphImpl")
            @TestDataPath("$PROJECT_ROOT")
            public class GrandchildGraphImpl {
              @Test
              public void testAllFilesPresentInGrandchildGraphImpl() {
                KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/BasicKeysUnusedReport/keys-unused/AppGraph/Impl/ChildGraphImpl/GrandchildGraphImpl"), Pattern.compile("^(.+)\\.kt$"), null, true);
              }
            }
          }
        }
      }
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/reports/DeeplyNestedGraphsKeysPopulatedReport")
  @TestDataPath("$PROJECT_ROOT")
  public class DeeplyNestedGraphsKeysPopulatedReport {
    @Test
    public void testAllFilesPresentInDeeplyNestedGraphsKeysPopulatedReport() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/DeeplyNestedGraphsKeysPopulatedReport"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/dump/reports/DeeplyNestedGraphsKeysPopulatedReport/keys-populated")
    @TestDataPath("$PROJECT_ROOT")
    public class Keys_populated {
      @Test
      public void testAllFilesPresentInKeys_populated() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/DeeplyNestedGraphsKeysPopulatedReport/keys-populated"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Nested
      @TestMetadata("compiler-tests/src/test/data/dump/reports/DeeplyNestedGraphsKeysPopulatedReport/keys-populated/AppGraph")
      @TestDataPath("$PROJECT_ROOT")
      public class AppGraph {
        @Test
        public void testAllFilesPresentInAppGraph() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/DeeplyNestedGraphsKeysPopulatedReport/keys-populated/AppGraph"), Pattern.compile("^(.+)\\.kt$"), null, true);
        }

        @Nested
        @TestMetadata("compiler-tests/src/test/data/dump/reports/DeeplyNestedGraphsKeysPopulatedReport/keys-populated/AppGraph/Impl")
        @TestDataPath("$PROJECT_ROOT")
        public class Impl {
          @Test
          public void testAllFilesPresentInImpl() {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/DeeplyNestedGraphsKeysPopulatedReport/keys-populated/AppGraph/Impl"), Pattern.compile("^(.+)\\.kt$"), null, true);
          }

          @Nested
          @TestMetadata("compiler-tests/src/test/data/dump/reports/DeeplyNestedGraphsKeysPopulatedReport/keys-populated/AppGraph/Impl/ChildGraphImpl")
          @TestDataPath("$PROJECT_ROOT")
          public class ChildGraphImpl {
            @Test
            public void testAllFilesPresentInChildGraphImpl() {
              KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/DeeplyNestedGraphsKeysPopulatedReport/keys-populated/AppGraph/Impl/ChildGraphImpl"), Pattern.compile("^(.+)\\.kt$"), null, true);
            }

            @Nested
            @TestMetadata("compiler-tests/src/test/data/dump/reports/DeeplyNestedGraphsKeysPopulatedReport/keys-populated/AppGraph/Impl/ChildGraphImpl/GrandChildGraphImpl")
            @TestDataPath("$PROJECT_ROOT")
            public class GrandChildGraphImpl {
              @Test
              public void testAllFilesPresentInGrandChildGraphImpl() {
                KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/DeeplyNestedGraphsKeysPopulatedReport/keys-populated/AppGraph/Impl/ChildGraphImpl/GrandChildGraphImpl"), Pattern.compile("^(.+)\\.kt$"), null, true);
              }

              @Nested
              @TestMetadata("compiler-tests/src/test/data/dump/reports/DeeplyNestedGraphsKeysPopulatedReport/keys-populated/AppGraph/Impl/ChildGraphImpl/GrandChildGraphImpl/GreatGrandChildGraphImpl")
              @TestDataPath("$PROJECT_ROOT")
              public class GreatGrandChildGraphImpl {
                @Test
                public void testAllFilesPresentInGreatGrandChildGraphImpl() {
                  KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/DeeplyNestedGraphsKeysPopulatedReport/keys-populated/AppGraph/Impl/ChildGraphImpl/GrandChildGraphImpl/GreatGrandChildGraphImpl"), Pattern.compile("^(.+)\\.kt$"), null, true);
                }
              }
            }
          }
        }
      }
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement")
  @TestDataPath("$PROJECT_ROOT")
  public class UnmatchedReplacement {
    @Test
    public void testAllFilesPresentInUnmatchedReplacement() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement/merging-unmatched-exclusions-fir")
    @TestDataPath("$PROJECT_ROOT")
    public class Merging_unmatched_exclusions_fir {
      @Test
      public void testAllFilesPresentInMerging_unmatched_exclusions_fir() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement/merging-unmatched-exclusions-fir"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement/merging-unmatched-exclusions-ir")
    @TestDataPath("$PROJECT_ROOT")
    public class Merging_unmatched_exclusions_ir {
      @Test
      public void testAllFilesPresentInMerging_unmatched_exclusions_ir() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement/merging-unmatched-exclusions-ir"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Nested
      @TestMetadata("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement/merging-unmatched-exclusions-ir/kotlin")
      @TestDataPath("$PROJECT_ROOT")
      public class Kotlin {
        @Test
        public void testAllFilesPresentInKotlin() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement/merging-unmatched-exclusions-ir/kotlin"), Pattern.compile("^(.+)\\.kt$"), null, true);
        }
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement/merging-unmatched-replacements-fir")
    @TestDataPath("$PROJECT_ROOT")
    public class Merging_unmatched_replacements_fir {
      @Test
      public void testAllFilesPresentInMerging_unmatched_replacements_fir() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement/merging-unmatched-replacements-fir"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement/merging-unmatched-replacements-ir")
    @TestDataPath("$PROJECT_ROOT")
    public class Merging_unmatched_replacements_ir {
      @Test
      public void testAllFilesPresentInMerging_unmatched_replacements_ir() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement/merging-unmatched-replacements-ir"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Nested
      @TestMetadata("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement/merging-unmatched-replacements-ir/kotlin")
      @TestDataPath("$PROJECT_ROOT")
      public class Kotlin {
        @Test
        public void testAllFilesPresentInKotlin() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement/merging-unmatched-replacements-ir/kotlin"), Pattern.compile("^(.+)\\.kt$"), null, true);
        }
      }
    }
  }
}
