// Copyright (C) 2026 Zac Sweers
// SPDX-License-Identifier: Apache-2.0
package dev.zacsweers.metro.compiler.fir

import org.jetbrains.kotlin.fir.backend.FirMetadataSource
import org.jetbrains.kotlin.fir.declarations.FirClass
import org.jetbrains.kotlin.fir.declarations.FirDeclarationDataKey
import org.jetbrains.kotlin.fir.declarations.FirDeclarationDataRegistry
import org.jetbrains.kotlin.ir.declarations.IrClass

/** FIR declaration attributes used by Metro to tag generated declarations with metadata. */
internal object MetroFirAttributes {
  /**
   * Marks a top-level class as having been generated by a
   * [MetroFirDeclarationGenerationExtension][dev.zacsweers.metro.compiler.api.fir.MetroFirDeclarationGenerationExtension].
   *
   * This is used to prevent contribution provider generation for these classes, since FIR cannot
   * generate top-level classes from other generated top-level classes.
   */
  object IsExtensionGenerated : FirDeclarationDataKey()
}

internal var FirClass.isExtensionGenerated: Boolean? by
  FirDeclarationDataRegistry.data(MetroFirAttributes.IsExtensionGenerated)

internal val IrClass.isExtensionGenerated: Boolean
  get() = (metadata as? FirMetadataSource.Class)?.fir?.isExtensionGenerated == true
